Completes attributions
edgexfoundry/edgex-cli pull request #291
Opened 2020-09-21 22:16 UTC by mkbhanda

1) Updates Makefile to include a test target
2) Includes go mod tidy and attributions test scripts (copied over from app-service-configurable)
3) Updates some go files per gofmt prescription
4) Adds Attributes.txt file that includes attributions per bin/test-attribution-txt.sh

2020-09-23 08:10 UTC, difince commented
@mkbhanda You missed to sign your commits https://github.com/edgexfoundry/edgex-cli/pull/291/checks?check_run_id=1146548916

2020-09-23 08:11 UTC, difince commented
@mkbhanda could you rebase, so the PR contains just your changes

2020-09-23 08:23 UTC, difince requested changes

2020-09-23 08:23 UTC, difince commented on cmd/device/device.go
> -func NewCommand() *cobra.Command {
This file `cmd/device/device.go` should be present that is why 
make test fails with 

> go: finding module for package github.com/edgexfoundry/edgex-cli/cmd/device
> cmd/root.go:25:2: no matching versions for query "latest"
> Makefile:29: recipe for target 'test' failed
> make: *** [test] Error 1

2020-09-23 08:23 UTC, difince commented on cmd/device/device.go
> -func NewCommand() *cobra.Command {
Rebase could help with this issue and will make the PR contains just the files you have really changed

2020-09-23 16:52 UTC, mkbhanda commented
Thank you @difince for catching the issues. Addressed them.

2020-09-24 13:24 UTC, difince approved these changes

2020-09-24 13:26 UTC, difince commented on cmd/device/device.go
> -func NewCommand() *cobra.Command {
make test still fails with me ..but I doubt that the problem is in my local environment. I will mege the PR and later investigate why  make test do not succeed with me.

2020-09-24 13:33 UTC, merged